// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIQI.Data;

#nullable disable

namespace PIQI.Data.Migrations
{
    [DbContext(typeof(PIQIDbContext))]
    partial class PIQIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("PIQI.Data.PrimaryUnitMart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeSystemMnemonic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSetMnemonic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UOMText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentSetMnemonic", "CodeSystemMnemonic", "CodeValue");

                    b.ToTable("PrimaryUnitMart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeSystemMnemonic = "REGEN_LOINC",
                            CodeValue = "100374-8",
                            ContentSetMnemonic = "PC_UOM",
                            UOMText = "[GPL'U]"
                        });
                });

            modelBuilder.Entity("PIQI.Data.RangeSetMart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeSystemMnemonic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSetMnemonic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("UOMText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentSetMnemonic", "CodeSystemMnemonic", "CodeValue");

                    b.ToTable("RangeSetMart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeSystemMnemonic = "REGEN_LOINC",
                            CodeValue = "2075-0",
                            ContentSetMnemonic = "PC_UOM_VALUE_RANGE",
                            MaxValue = 400.0,
                            MinValue = 0.0,
                            UOMText = "mmol/L"
                        });
                });

            modelBuilder.Entity("PIQI.Data.TextMart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSetMnemonic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentSetMnemonic");

                    b.ToTable("TextMart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentSetMnemonic = "UCUM",
                            TextValue = "mg/L"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
